# _config.yaml
## Jekyll configuration for curtisfree.com.

# Overall config:
title:                   "Curtis Free"
author:                  "Curtis Free"
email:                   cf@curtisfree.com
description:             "Husband &middot; Dad &middot; Geek"
url:                     https://curtisfree.com
permalink:               /:categories/:year/:month/:day/:title/
exclude:                 [ CNAME, compose.yaml, .markdownlint.yaml, README.md ]
include:                 [ .well-known ]

# theme (colors)
colors:
    dark: "#222021"
    light: "white"
    accent: "olivedrab"

# github
code:
    url: &github https://github.com/cfree3

# license
license:
    name: "CC BY-SA 4.0"
    url:  https://creativecommons.org/licenses/by-sa/4.0/

# ownership verification
verification:
    bluesky:
        key: "did:plc:6ybpe5xp6lobzjhoa2kow5gn"
    google:
        key: "snYf1sv_GydvZGyzaJsZ_rz-1OaXUhxdREvfm-ExzT8"

# "me" links (hidden on page but used for verification)
me:
    - name: Bluesky
      url:  https://bsky.app/profile/curtisfree.com
    - name: GitHub
      url:  *github
    - name: Instagram
      url:  https://instagram.com/curtisafree
    - name: Mastodon
      url:  https://mastodon.social/@curtisafree
    - name: Reddit
      url:  https://www.reddit.com/user/curtisafree
    - name: Threads
      url:  https://www.threads.net/@curtisafree
    - name: Twitter
      url:  https://twitter.com/curtisafree

# markup
markdown: kramdown
kramdown:
    smart_quotes: [ "apos", "apos", "quot", "quot" ]
    syntax_highlighter_opts:
        disable: true

# YAML defaults:
defaults:
    -
        scope:
            path:  ""
            type:  "pages"
        values:
            title: ""
