# _config.yml
# Jekyll configuration for CurtisFree.com site & blog.
url:       http://curtisfree.com
markdown:  kramdown
permalink: /content/blog/:year/:month/:day/:title.html
exclude:   [README.md]
