# _config.yml
## Jekyll configuration for curtisfree.com.

# Overall config:
name:                    "Curtis Free"
author:                  "Curtis Free"
email:                   cf@curtisfree.com
description:             "Husband, father, geek, progressive."
url:                     https://curtisfree.com
color:                   olivedrab
license-name:            "Creative Commons Attribution-ShareAlike 4.0 International License"
license-url:             https://creativecommons.org/licenses/by-sa/4.0/
instagram-url:           https://instagram.com/curtisafree
github-url:              https://github.com/cfree3
twitter-url:             https://twitter.com/curtisafree
google-verification-key: "snYf1sv_GydvZGyzaJsZ_rz-1OaXUhxdREvfm-ExzT8"
markdown:                kramdown
permalink:               /blog/:year/:month/:day/:title/
exclude:                 [README.md]

# YAML defaults:
defaults:
    -
        scope:
            path:  ""
            type:  "pages"
        values:
            title: ""
